PanelType: SSpanel

ApiConfig:
  ApiHost: https://example.com
  ApiKey: SecretKey
  NodeID: 0
  NodeType: v2ray
  Timeout: 5
  EnableVless: false
  EnableXTLS: false
  SpeedLimit: 0
  DeviceLimit: 0
  RuleListPath: /tmp/xrayr/rulelist
  DisableCustomConfig: false

ControllerConfig:
  ListenIP: 127.0.0.1
  SendIP: 0.0.0.0
  UpdatePeriodic: 60
  EnableDNS: true
  DNSType: UseIP
  DisableUploadTraffic: false
  DisableGetRule: false
  DisableIVCheck: false
  DisableSniffing: false
  EnableProxyProtocol: false

  AutoSpeedLimitConfig:
    Limit: 0
    WarnTimes: 0
    LimitSpeed: 0
    LimitDuration: 0

  GlobalDeviceLimitConfig:
    Enable: false
    RedisNetwork: tcp
    RedisAddr: 127.0.0.1:6379
    RedisUsername: xrayr
    RedisPassword: Password
    RedisDB: 0
    Timeout: 5
    Expiry: 60

  EnableFallback: false
  FallBackConfigs:
    - SNI:
      Alpn:
      Path:
      Dest: 80
      ProxyProtocolVer: 0

  CertConfig:
    CertMode: none
    RejectUnknownSni: false
    CertDomain: example.com
    CertFile: /tmp/xrayr/cert/example.com.cert
    KeyFile: /tmp/xrayr/cert/example.com.key
    Provider: cloudflare
    Email: admin@example.com
    DNSEnv:
      CF_DNS_API_TOKEN: ApiToken
